show databases;
create database if not exists vmart;
use vmart;
show tables;
select * from vmart.products;
select * from vmart.products_specification;
select * from vmart.products_picList;
insert into vmart.products values (1,'111','1111','11','11','1','1','1','1');
insert into vmart.products values (2,'2222','2222','22','22','2','2','2','2');
select * from vmart.Seller;
select * from vmart.hibernate_sequence;
select * from vmart.categories;
select * from vmart.customer_details;
select * from vmart.discounts;
select * from vmart.products;
delete from vmart.products where pid = 2;
select * from vmart.categories where catName="test";
insert into vmart.discounts values (1,10.00);
select * from vmart.discounts where percentage = 10.00 ;
delete from vmart.discounts where percentage =  10;
desc vmart.products;
insert into vmart.PromoImage values(1,'Img1','https://www.google.com','https://i.picsum.photos/id/0/5616/3744.jpg');
insert into vmart.PromoImage values(2,'Img2','https://www.google.com','https://i.picsum.photos/id/1/5616/3744.jpg');
insert into vmart.PromoImage values(3,'Img3','https://www.google.com','https://i.picsum.photos/id/1027/5616/3744.jpg');
delete from vmart.customer_details where cid >1;
delete from vmart.customer_details where next_val = 7;
drop table vmart.customer_details;
drop table vmart.hibernate_sequence;
drop database vmart;

